# Generated by Django 3.1 on 2021-07-15 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
    ]
