# Generated by Django 3.1 on 2021-07-16 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_remove_detail_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='author_id',
            field=models.ForeignKey(default='noname', on_delete=django.db.models.deletion.PROTECT, to='accounts.customuser', verbose_name='筆者'),
            preserve_default=False,
        ),
    ]
