# Generated by Django 3.1 on 2021-07-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_detail_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='main_material',
            field=models.CharField(default='無し', max_length=50, verbose_name='アレンジ元'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='material',
            field=models.TextField(blank=True, null=True, verbose_name='材料'),
        ),
    ]
